version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6378:6379"
    volumes:
      - "./redis:/data"
  postgres:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      # Be aware that indexed data are located in "/chroma/chroma/"
      # Default configuration for persist_directory in chromadb/config.py
      # Read more about deployments: https://docs.trychroma.com/deployment
      - ./chroma-data:/chroma/chroma
    command: "--workers 1 --host 0.0.0.0 --port 8000 --proxy-headers --log-config chromadb/log_config.yml --timeout-keep-alive 30"
    environment:
      - IS_PERSISTENT=TRUE
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3
  neo4j:
    image: neo4j:5.21.0
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./neo4j/data:/data
      # - ./neo4j/logs:/logs
      # - ./neo4j/conf:/conf
      # - ./neo4j/import:/import
      #- ./metrics/server2:/metrics
      #- ./licenses/server2:/licenses
      #- ./ssl/server2:/ssl
    environment:
      - NEO4J_AUTH=neo4j/password
